### ISSUE TITLE
eusurdfのモデル変換で/tmpにファイルを作るが他のユーザが上書きできない

### ISSUE THREAD

**Issue by mmurooka** [jsk-ros-pkg/jsk_model_tools#124]
特にPR2で起きていますが，
eusからurdfにモデル変換するときに/tmpに途中生成のcolladaファイルができるようになっていて，
ユーザaaaが変換したcolladaが/tmpに残っていると，
ユーザbbbが同じ名前のcolladaファイルを/tmpに作れず，止まってしまう，
という問題がおきています．

どのように解決するのがよろしいでしょうか．
１．コンパイルのたびに，/tmpにランダムな名前のディレクトリを作って，そこにcolladaを置く
２．colladaファイルを作るときに誰でも消せるように権限を付ける
くらいしか思いつかず
１．でやってみようかと思いますがよろしいでしょうか．

**Comment by mmurooka** [comment]
ありがとうございます．

eusでランダムに作ったディレクトリの名前を知りたいのですが，
良い方法ありますでしょうか．
eusのプログラムの中でディレクトリを作るので構いません．

**Comment by snozawa** [comment]
> eusでランダムに作ったディレクトリの名前を知りたいのですが，
> 良い方法ありますでしょうか．
> eusのプログラムの中でディレクトリを作るので構いません．

これが必要な状況は、ちょっと複雑な状況かな、とおもいます。
変換のフロー図をみなおしてみて、もうちょい別な解法があるかも検討してみるとよいですね。
なんとか途中生成ファイルをお互いにやりとりしなくてすむように、などなど

それで、上記をもしやるとしたらなにかコンフリクトしない名前づけでルール決めとくとかはあるかもしれません。
eusのプロセスのPIDの名前をつける、とか。

**Comment by garaemon** [comment]
乱数で適当に数字をくっつけて、そのファイルが被っていないかを確認して繰り返し行う、とか色々とやり方はある気がします。

**Comment by mmurooka** [comment]
https://github.com/jsk-ros-pkg/jsk_model_tools/pull/126 で解決しているのでcloseします．
