### ISSUE TITLE
Why the output of Kinect's color attribue red and blue is reversed?

### ISSUE THREAD

**Issue by aginika** [jsk-ros-pkg/jsk_model_tools#133]
Gazebo
![gazebp_pr2](https://cloud.githubusercontent.com/assets/3803922/8981699/6eda2cc2-36f5-11e5-8422-976b0139827e.png)

Rviz
![pr2_rviz](https://cloud.githubusercontent.com/assets/3803922/8981705/79f36a4c-36f5-11e5-8b84-989dae168c87.png)

**Comment by k-okada** [comment]
bug, write PR and commit to upstream

--
◉ Kei Okada

**Comment by aginika** [comment]
ok, understood

**Comment by aginika** [comment]
This seems to be problem only in INDIGO

**Comment by aginika** [comment]
https://github.com/PR2/pr2_common/pull/244
