### ISSUE TITLE
Request for new version release

### ISSUE THREAD

**Issue by snozawa** [jsk-ros-pkg/jsk_model_tools#140]
Request for new version release to update euscollada-robot.l for downsteram tests.

**Comment by garaemon** [comment]
I will

**Comment by snozawa** [comment]
Thanks!

**Comment by garaemon** [comment]
0.1.13 https://github.com/jsk-ros-pkg/jsk_model_tools/commit/fb77908f35e49292d2e8028432bf0ddb1aafe7ed

**Comment by garaemon** [comment]
https://mail.google.com/mail/u/0/#inbox/14f83d127a03e9f4
released

deb will be released in one or two days.

**Comment by k-okada** [comment]
ran bloom -> https://github.com/ros/rosdistro/pull/9339

--
◉ Kei Okada

**Comment by k-okada** [comment]
@snozawa

you can use
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/add_tag/build?delay=0sec to
release by yourself
select repository and push build button, and check with console output (
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/add_tag/131/console), if
that is ok, chosse "FALSE" and build again

--
◉ Kei Okada
