### ISSUE TITLE
release request: eusurdf

### ISSUE THREAD

**Issue by furushchev** [jsk-ros-pkg/jsk_model_tools#202]
`eusurdf` version is now 0.2.5 and there are many changes on generated models.

**Comment by k-okada** [comment]
https://github.com/ros/rosdistro/pull/14117

--
◉ Kei Okada


2017-03-07 15:17 GMT+09:00 Furushchev <notifications@github.com>:

**Comment by furushchev** [comment]
@k-okada Thanks. BTW, I'm worried that models will not changed until newer euslisp is released?

**Comment by k-okada** [comment]
yes, you're right -> https://github.com/ros/rosdistro/pull/14119

--
◉ Kei Okada


2017-03-07 15:38 GMT+09:00 Furushchev <notifications@github.com>:

**Comment by furushchev** [comment]
@k-okada Thank you again!!
